import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='text-center mt-[35vh]'>
          <h1 className='text-2xl'>Welcome to Elijah&apos;s personal site</h1>
          <p>Look around to learn more about Elijah and see his current catches for the year!</p>
        </div>
      </main>
    </div>
  )
}
