import Head from 'next/head'
import axios from 'axios'
import GitCard from '../components/GitCard'
import { BASE_URL } from '../utils/constants'

export default function Home({repo}) {
  return (
    <div>
      <Head>
        <title>Elijah Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className='text-center mt-[10vh] mb-10'>
          <h1 className='text-3xl'>Welcome to Elijah&apos;s personal site</h1>
          <p className='text-lg'>Look around to learn more about Elijah, his git repos, and some catches for the year!</p>
        </div>
        <div className='flex justify-start gap-5 flex-wrap m-5'>
        {repo.map((info) => (
          <GitCard key={info._id} repo={info}/>
        ))}
        </div>
      </main>
    </div>
  )
}

export const getServerSideProps = async (context) => {
  const res = await axios.get(`${BASE_URL}/api/repo`);
  return {
    props: {repo: res.data}
  }
}